### ISSUE TITLE
JDK proxy exception when method is toString ...

### ISSUE THREAD

**Issue by liuzhengyang** [liuzhengyang/simple-rpc#5]
java.lang.NoSuchMethodException: com.github.liuzhengyang.simplerpc.core.HelloImpl.toString()
	at java.lang.Class.getDeclaredMethod(Class.java:2130)
	at com.github.liuzhengyang.simplerpc.core.RpcServerHandler.channelRead0(RpcServerHandler.java:31)
	at com.github.liuzhengyang.simplerpc.core.RpcServerHandler.channelRead0(RpcServerHandler.java:17)

**Comment by liuzhengyang** [comment]
#14
